import { GeneralAbilitiesData, InvestigativeAbilitiesData } from "./types";

export const investigativeAbilities: InvestigativeAbilitiesData = {
  Academic: [
    { name: "Anthropology" },
    { name: "Archaeology" },
    { name: "Botany" },
    { name: "Cybe Culture" },
    { name: "Forensic Accounting" },
    { name: "Forensic Psychology" },
    { name: "Geology" },
    { name: "History, Balla" },
    { name: "History, Combine" },
    { name: "History, Durugh" },
    { name: "History, Human" },
    { name: "History, Kch-Thk" },
    { name: "History, Tavak" },
    { name: "Law" },
    { name: "Linguistics" },
    { name: "Vas Mal Culture" },
    { name: "Xenoculture" },
    { name: "Zoology" },
  ],
  Interpersonal: [
    { name: "Bullshit Detector" },
    { name: "Bureaucracy" },
    { name: "Cop Talk" },
    { name: "Downside" },
    { name: "Flattery" },
    { name: "Flirting" },
    { name: "Impersonate" },
    { name: "Inspiration" },
    { name: "Interrogation" },
    { name: "Intimidation" },
    { name: "Negotiation" },
    { name: "Reassurance" },
    { name: "Respect" },
  ],
  Technical: [
    { name: "Astronomy" },
    { name: "Bio Signatures" },
    { name: "Chemistry" },
    { name: "Data Retrieval" },
    { name: "Decryption" },
    { name: "Energy Signatures" },
    { name: "Evidence Collection" },
    { name: "Explosive Devices" },
    { name: "Forensic Anthropology" },
    { name: "Forensic Engineering" },
    { name: "Holo Surveillance" },
    { name: "Imaging" },
    { name: "Industrial Design" },
    { name: "Kinetics" },
    { name: "Virology" },
  ],
  Special: [
    { name: "Consciousness Simulation" },
    { name: "Dreamsight" },
    { name: "Neurosight" },
    { name: "Timesight" },
  ],
};

export const generalAbilities: GeneralAbilitiesData = {
  General: [
    { name: "Athletics", refreshesDaily: true },
    { name: "Battle Console" },
    { name: "Business Affairs" },
    { name: "Communications Intercept" },
    { name: "Emotion Suppression (Balla)" },
    { name: "Enhancement Integration (Cybe)" },
    { name: "Farsight (Vas Mal)" },
    { name: "Filch" },
    { name: "Ground Craft" },
    {
      name: "Health",
      max: 15,
      min: -12,
      rating: 1,
      pool: 1,
      showTracker: true,
    },
    { name: "Helm Control" },
    { name: "Infiltration" },
    { name: "Medic" },
    { name: "Migrate Consciousness (Kch-Thk)" },
    { name: "Naval Tactics" },
    { name: "Neural Rewiring (Cybe)" },
    { name: "Resist Battle Frenzy (Tavak)" },
    { name: "Pathway Amplification (Vas Mal)" },
    { name: "Probability Override (Vas Mal)" },
    { name: "Phase (Durugh)" },
    { name: "Preparedness" },
    { name: "Psychic Vitality (Vas Mal)" },
    { name: "Public Relations" },
    { name: "Scuffling", refreshesDaily: true },
    { name: "Sense Trouble" },
    { name: "Shooting", refreshesDaily: true, goesFirstInCombat: true },
    { name: "Shuttle Craft" },
    { name: "Surveillance" },
    { name: "Systems Design" },
    { name: "Systems Repair" },
    { name: "Viro Manipulation" },
  ],
};
