import { GeneralAbilitiesData, InvestigativeAbilitiesData } from "./types";

export const investigativeAbilities: InvestigativeAbilitiesData = {
  Academic: [
    { name: "Accounting" },
    { name: "Anthropology" },
    { name: "Archaeology" },
    { name: "Architecture" },
    { name: "Art History" },
    { name: "Biology" },
    { name: "Chtulhu Mythos" },
    { name: "Cryptography" },
    { name: "Geology" },
    { name: "History" },
    { name: "Languages", hasSpecialities: true },
    { name: "Law" },
    { name: "Library Use" },
    { name: "Medicine" },
    { name: "Occult" },
    { name: "Physics" },
    { name: "Theology" },
  ],
  Interpersonal: [
    { name: "Assess Honesty" },
    { name: "Bargain" },
    { name: "Bureaucracy" },
    { name: "Cop Talk" },
    { name: "Credit Rating" },
    { name: "Flattery" },
    { name: "Interrogation" },
    { name: "Intimidation" },
    { name: "Oral History" },
    { name: "Reassurance" },
    { name: "Streetwise" },
  ],
  Technical: [
    { name: "Art" },
    { name: "Astronomy" },
    { name: "Chemistry" },
    { name: "Craft" },
    { name: "Evidence Collection" },
    { name: "Forensics" },
    { name: "Locksmith" },
    { name: "Outdoorsman" },
    { name: "Pharmacy" },
    { name: "Photography" },
  ],
};

export const generalAbilities: GeneralAbilitiesData = {
  General: [
    { name: "Athletics", refreshesDaily: true },
    { name: "Conceal" },
    { name: "Disguise", canBeInvestigative: true },
    { name: "Driving", refreshesDaily: true },
    { name: "Electrical Repair" },
    { name: "Explosives", canBeInvestigative: true },
    { name: "Filch" },
    { name: "Firearms", refreshesDaily: true },
    { name: "First Aid" },
    { name: "Fleeing", refreshesDaily: true },
    {
      name: "Health",
      max: 15,
      min: -12,
      rating: 1,
      pool: 1,
      showTracker: true,
    },
    { name: "Hypnosis" },
    { name: "Mechanical Repair" },
    { name: "Piloting", refreshesDaily: true },
    { name: "Preparedness" },
    { name: "Psychoanalysis" },
    { name: "Riding", refreshesDaily: true },
    {
      name: "Sanity",
      max: 15,
      min: -12,
      rating: 1,
      pool: 1,
      showTracker: true,
    },
    { name: "Scuffling", refreshesDaily: true },
    { name: "Sense Trouble" },
    { name: "Shadowing" },
    {
      name: "Stability",
      max: 15,
      min: -12,
      rating: 1,
      pool: 1,
      showTracker: true,
    },
    { name: "Stealth" },
    { name: "Weapons", refreshesDaily: true },
  ],
};
